[package]
name = "universal_canister"
version = "0.1.0"
edition = "2021"

[dependencies]
wee_alloc = "0.4.3"
lazy_static = "1.4.0"
candid = "0.8.1"
serde = { version = "1.0.99", features = ["derive"] }
