[package]
name = "ic-interfaces-transport"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-base-types = { path = "../../types/base_types" }
phantom_newtype = { path = "../../phantom_newtype" }
serde = { version = "1.0.99", features = ["derive"] }
serde_bytes = "0.11"
strum = "0.24"
strum_macros = "0.24"
tower = { version = "0.4.11", features = ["util"] }
