queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=test (ubuntu-latest)
      - status-success=test (macos-latest)
      - base=master
      - label=automerge-squash
    merge_conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=test (ubuntu-latest)
      - status-success=test (macos-latest)
      - base=master
      - label=automerge-squash
    commit_message_template: |
      {{title}}

      {{body}}
    merge_method: squash

pull_request_rules:
  - name: Automatic merge (squash)
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=test (ubuntu-latest)
      - status-success=test (macos-latest)
      - base=master
      - label=automerge-squash
    actions:
      delete_head_branch: {}
      queue:
  - name: Clean up automerge tags
    conditions:
      - closed
    actions:
      label:
        remove:
          - automerge-squash
          - autoclose
