queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=test (ubuntu-latest)
      - status-success=test (macos-latest)
      - base=master
      - label=automerge-squash

pull_request_rules:
  - name: Automatic merge (squash)
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=test (ubuntu-latest)
      - status-success=test (macos-latest)
      - base=master
      - label=automerge-squash
    actions:
      queue:
        method: squash
        name: default
        commit_message: title+body
      delete_head_branch: {}
  - name: Clean up automerge tags
    conditions:
      - closed
    actions:
      label:
        remove:
        - automerge-squash
        - autoclose
