[package]
name = "httpbin-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
axum-server = { version = "0.5.1", features = ["tls-openssl"] }
clap = { version = "4.0", features = ["derive"] }
rustls = "0.21.1"
rustls-pemfile = "1.0.2"
serde_json = { version = "1.0" }
tokio = { version = "1.0", features = ["rt-multi-thread"] }
