[package]
name = "ic-interfaces-registry-mocks"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-interfaces-registry = { path = "../" }
ic-base-types = { path = "../../../types/base_types" }
ic-types = { path = "../../../types/types" }
mockall = "0.11.2"
