[package]
name = "ic-interfaces-registry"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-types = { path = "../..//types/types" }
prost = "0.11.0"
serde = { version = "1.0.99", features = ["derive"] }

