[package]
name = "ic-interfaces-transport-mocks"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-interfaces-transport = { path = "../" }
ic-base-types = { path = "../../../types/base_types" }
mockall = "0.11.2"
